name: 'Cachix'
description: 'nix-build with the help of caching to Cachix'
author: 'Domen Kožar'
inputs:
  name:
    description: 'Name of a cachix cache to push and pull/substitute'
    required: true
  extraPullNames:
    description: 'Comma-separated list of names for extra cachix caches to pull/substitute'
  authToken:
    description: 'Authentication token for Cachix, needed only for private cache access'
  signingKey:
    description: 'Signing key secret retrieved after creating binary cache on https://cachix.org'
  skipPush:
    description: 'Set to true to disable pushing build results to the cache'
branding:
  color: 'blue'
  icon: 'database'
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/main/index.js'
