name: "cachix-action test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  public-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - run: yarn install --frozen-lockfile
    - run: yarn build
    # check if typescript generation was committed
    - run: git diff --exit-code
    - uses: cachix/install-nix-action@v13
    - name: Test public cache
      uses: ./
      with:
        name: cachix-action
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build test.nix

  public-cache-no-signing-key:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: cachix/install-nix-action@v13
    - name: Test public cache no signing key
      uses: ./
      with:
        name: cachix-action
    - run: nix-build test.nix

  private-cache:
    if: ${{ github.ref == 'refs/heads/master' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: cachix/install-nix-action@v13
    - name: Test private cache
      uses: ./
      with:
        name: cachix-action-private
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY_PRIVATE }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build test.nix

  installCommand:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.4
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: cachix/install-nix-action@v13
    - name: Test private cache
      uses: ./
      with:
        name: cachix-action
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        installCommand: 'nix-env -j8 -f https://cachix.org/api/v1/install -iA cachix'
    - run: nix-build test.nix

  nix-master:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with: 
        nix_path: nixpkgs=channel:nixos-20.03
        install_url: https://nixos-nix-install-tests.cachix.org/serve/lb41az54kzk6j12p81br4bczary7m145/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - name: Test public cache
      uses: ./
      with:
        name: cachix-action
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build test.nix