name: "cachix-action test"
on:
  pull_request:
  push:    
    branches:
      - master

jobs:
  public-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: yarn build
    # check if typescript generation was committed
    - run: git diff --exit-code
    - uses: cachix/install-nix-action@v10
    - name: Test public cache
      uses: ./
      with:
        name: cachix-action
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build test.nix

  public-cache-no-signing-key:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: cachix/install-nix-action@v11
    - name: Test public cache no signing key
      uses: ./
      with:
        name: cachix-action
    - run: nix-build test.nix

  private-cache:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: cachix/install-nix-action@v11
    - name: Test private cache
      uses: ./
      with:
        name: cachix-action-private
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY_PRIVATE }}'
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build test.nix

  installCommand:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - uses: cachix/install-nix-action@v11
    - name: Test private cache
      uses: ./
      with:
        name: cachix-action
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        installCommand: 'nix-env -f https://cachix.org/api/v1/install -iA cachix'
    - run: nix-build test.nix
