name: "nix-cachix test"
on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, macos]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - run: yarn test
    - uses: cachix/install-nix-action@v1
    - name: Install & Build
      uses: ./
      with:
        cachixPush: cachix-action
        file: test.nix
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'